# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

In [ ]:
! pip install numpy

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.__version__

'1.24.2'

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
vec = np.zeros(10)
vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
f"{vec.size * vec.itemsize} bytes"

'80 bytes'

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
vec = np.zeros(10)
vec[4] = 1
vec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
vec = np.arange(10, 50)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
vec[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(0, 9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.rand(3, 3, 3)

array([[[0.84049159, 0.63965337, 0.86280302],
        [0.98131799, 0.77015546, 0.87170931],
        [0.92275738, 0.85454377, 0.07772533]],

       [[0.15548693, 0.67592031, 0.69257018],
        [0.61873443, 0.03845976, 0.73606634],
        [0.0972117 , 0.61054632, 0.98879367]],

       [[0.43839113, 0.68210705, 0.30672429],
        [0.15606258, 0.5168046 , 0.82813167],
        [0.55694027, 0.95850469, 0.21702173]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
vec3d = np.random.rand(3, 3, 3)
f"min = {vec3d.min()}; max= {vec3d.max()}"

'min = 0.0233948658790456; max= 0.9194217550799307'

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
vec = np.random.rand(10)
print(vec)
vec.mean()

[0.76718533 0.70627732 0.49633249 0.97846766 0.57298761 0.38926134
 0.48460885 0.21863464 0.28471359 0.1700406 ]


0.5068509424527726

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
vec2d = np.ones((5, 5))
vec2d[1:-1, 1:-1] = 0
vec2d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
vec2d = np.ones((4, 4))
np.pad(vec2d, pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
vec2d = np.zeros((5, 5), int)
np.fill_diagonal(vec2d, [1, 2, 3, 4])
vec2d

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 1]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
np.unravel_index(99, (6, 7, 8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
vec = np.array([[0,1], [1,0]])
np.tile(vec, (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
matr = np.random.randint(1, 5, size=(5,5))
max, min = matr.max(), matr.min()
matr = (matr-min)/(max-min)
matr

array([[0.33333333, 0.33333333, 1.        , 0.33333333, 1.        ],
       [0.66666667, 0.66666667, 1.        , 0.33333333, 0.        ],
       [0.33333333, 0.66666667, 0.        , 0.33333333, 0.66666667],
       [1.        , 0.        , 0.66666667, 1.        , 0.66666667],
       [0.33333333, 1.        , 0.33333333, 0.33333333, 0.66666667]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
color = np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
np.ones((5,3)) @ np.ones((3,2))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
vec = np.arange(11)
vec[(vec>3) & (vec<8)] *= -1
vec

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

не понял

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

1 - ворнинг

2 - ворнинг

3 - самое маленькое число для float

#### 29. How to round away from zero a float array ? (★☆☆)

вообще нет идей

#### 30. How to find common values between two arrays? (★☆☆)

In [27]:
vec1 = np.random.randint(0,10,10)
print(vec1)
vec2 = np.random.randint(0,10,10)
print(vec2)
np.intersect1d(vec1,vec2)

[7 8 0 9 0 8 7 1 7 2]
[9 9 2 2 8 7 0 4 1 6]


array([0, 1, 2, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

не знаю

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [28]:
print(np.datetime64('today') - np.timedelta64(1))
print(np.datetime64('today'))
print(np.datetime64('today') + np.timedelta64(1))

2023-03-31
2023-04-01
2023-04-02


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [29]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [30]:
A = np.ones(3)
B = np.ones(3)*2
print(A, B)

np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

[1. 1. 1.] [2. 2. 2.]


array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [31]:
vec = np.random.uniform(0,10,10)

print(vec - vec%1)
print(vec // 1)
print(np.floor(vec))
print(vec.astype(int))
print(np.trunc(vec))

[1. 9. 0. 8. 3. 3. 7. 5. 1. 6.]
[1. 9. 0. 8. 3. 3. 7. 5. 1. 6.]
[1. 9. 0. 8. 3. 3. 7. 5. 1. 6.]
[1 9 0 8 3 3 7 5 1 6]
[1. 9. 0. 8. 3. 3. 7. 5. 1. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [32]:
matr = np.zeros((5,5), dtype=int)
matr += np.arange(5, dtype=int)
matr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [33]:
def generate():
    for x in range(10):
        yield x

np.fromiter(generate(),dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [34]:
np.linspace(0,1,11)[1:-1]

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [35]:
vec = np.random.random(10)
vec.sort()
vec

array([0.14927355, 0.25840276, 0.3335113 , 0.46033451, 0.4739854 ,
       0.49020478, 0.60192042, 0.62752836, 0.65674927, 0.83052546])

#### 41. How to sum a small array faster than np.sum? (★★☆)

не знаю

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [36]:
vec1 = np.random.randint(0,2,5)
vec2 = np.random.randint(0,2,5)
np.array_equal(vec1, vec2)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [37]:
vec = np.zeros(10)
vec.flags.writeable = False
vec[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [38]:
matr = np.random.random((10,2))
print(matr)
vec1, vec2 = matr[:,0], matr[:,1]
print(np.sqrt(vec1**2+vec2**2))
print(np.arctan2(vec2,vec1))

[[0.65802452 0.53744247]
 [0.8135904  0.64921857]
 [0.63813749 0.16675564]
 [0.26888468 0.75999547]
 [0.00273429 0.50990544]
 [0.94405232 0.33728243]
 [0.35208588 0.51373475]
 [0.78745554 0.74319885]
 [0.46677015 0.93361855]
 [0.4637722  0.19076949]]
[0.84961208 1.0408718  0.65956569 0.80615884 0.50991277 1.002494
 0.62280644 1.08278842 1.04379978 0.50147548]
[0.6848721  0.67350029 0.25560048 1.23074224 1.56543404 0.3431375
 0.96997334 0.75649264 1.10718224 0.39024649]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [39]:
vec = np.random.random(10)
print(vec)
vec[vec.argmax()] = 0
vec

[0.67688764 0.50728906 0.10204413 0.98068638 0.46740977 0.17573619
 0.8498357  0.58822174 0.77955547 0.40273159]


array([0.67688764, 0.50728906, 0.10204413, 0.        , 0.46740977,
       0.17573619, 0.8498357 , 0.58822174, 0.77955547, 0.40273159])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [40]:
matr = np.zeros((5,5), [('x',float),('y',float)])

matr['x'], matr['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
matr

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [41]:
matr_1 = np.arange(8)
matr_2 = matr_1 + 0.5
matr_3 = 1.0 / np.subtract.outer(matr_1, matr_2)
np.linalg.det(matr_3)

3638.1636371179666

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [42]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [43]:
np.set_printoptions(threshold=float("inf"))
np.zeros((20,20))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [44]:
vec1 = np.arange(100)
vec2 = np.random.uniform(0,100)
vec1[(np.abs(vec1-vec2)).argmin()]

43

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [45]:
np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),('color',    [ ('r', float, 1),('g', float, 1),('b', float, 1)])])

/tmp/ipykernel_1722/1457198310.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),('color',    [ ('r', float, 1),('g', float, 1),('b', float, 1)])])


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [46]:
vec = np.random.random((10,2))
vec_x, vec_y = np.atleast_2d(vec[:,0], vec[:,1])
np.sqrt( (vec_x-vec_x.T)**2 + (vec_y-vec_y.T)**2)

array([[0.        , 0.26127789, 0.68916991, 0.37049861, 0.52116585,
        0.52888627, 0.63309635, 0.57197514, 0.30757305, 0.20368188],
       [0.26127789, 0.        , 0.57759919, 0.57159233, 0.73289278,
        0.61786071, 0.83316701, 0.7155978 , 0.29419215, 0.44163037],
       [0.68916991, 0.57759919, 0.        , 1.05930263, 1.20505089,
        0.4670722 , 0.83742778, 0.62526724, 0.38600437, 0.88541109],
       [0.37049861, 0.57159233, 1.05930263, 0.        , 0.16169918,
        0.83088568, 0.77872987, 0.81560114, 0.67530457, 0.18065793],
       [0.52116585, 0.73289278, 1.20505089, 0.16169918, 0.        ,
        0.93798052, 0.82503166, 0.89927439, 0.81915312, 0.31985707],
       [0.52888627, 0.61786071, 0.4670722 , 0.83088568, 0.93798052,
        0.        , 0.37117282, 0.15863983, 0.33017567, 0.65425483],
       [0.63309635, 0.83316701, 0.83742778, 0.77872987, 0.82503166,
        0.37117282, 0.        , 0.21675121, 0.60831928, 0.64402817],
       [0.57197514, 0.7155978 , 0.6252672

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

не знаю

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [47]:
from io import StringIO


s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11''')

np.genfromtxt(s, delimiter=",", dtype=int)

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

не знаю

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [48]:
sigma, mu = 1.0, 0.0

vec_x, vec_y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
vec_d = np.sqrt(vec_x*vec_x+vec_y*vec_y)

np.exp(-( (vec_d-mu)**2 / ( 2.0 * sigma**2 ) ) )

array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [49]:
n = 10
p = 3
matr = np.zeros((n,n))
np.put(matr, np.random.choice(range(n*n), p, replace=False),1)
matr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [50]:
vec = np.random.rand(5, 10)
vec = vec - vec.mean(axis=1, keepdims=True)
vec

array([[ 0.33009933, -0.17095717, -0.05180864, -0.05146461,  0.2040751 ,
        -0.37508389,  0.2454579 ,  0.14418913, -0.47041255,  0.19590541],
       [ 0.39457024,  0.4039262 ,  0.46762786,  0.26277653, -0.10536219,
        -0.35915717, -0.51292695, -0.5156704 , -0.27323311,  0.23744899],
       [ 0.34178555, -0.43665013, -0.18803601,  0.16185973, -0.38384894,
         0.45196373,  0.25510438, -0.24414395, -0.10251637,  0.14448201],
       [-0.02755568,  0.09957954, -0.02260824, -0.24164791, -0.39968533,
         0.29674722,  0.23732449,  0.24551436,  0.25372458, -0.44139303],
       [ 0.25047377, -0.31286961,  0.24160479, -0.30134314, -0.17141073,
        -0.08736538,  0.10982681,  0.21664346, -0.10776363,  0.16220366]])

#### 59. How to sort an array by the nth column? (★★☆)

In [51]:
vec = np.random.randint(0,10,(3,3))
vec[vec[:,0].argsort()]

array([[1, 1, 6],
       [7, 3, 1],
       [8, 3, 7]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [52]:
vec = np.random.randint(0,3,(3,10))
(~vec.any(axis=0)).any()

False

#### 61. Find the nearest value from a given value in an array (★★☆)

In [53]:
vec = np.random.randint(0, 10, 10)
print(vec)
vec.flat[np.abs(vec - 4.6).argmin()]

[1 6 9 3 7 2 6 3 6 4]


4

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

не знаю

#### 63. Create an array class that has a name attribute (★★☆)

In [54]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

array = NamedArray(np.arange(10), "range_10")
array.name

'range_10'

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [55]:
vec1 = np.ones(10)
vec2 = np.random.randint(0,len(vec1),20)
np.add.at(vec1, vec2, 1)

vec1

array([3., 3., 5., 2., 2., 4., 3., 3., 2., 3.])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [56]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
F

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [57]:
w, h = 256, 256

vec = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(vec.reshape(-1, 3), axis=0)
len(colors)

64

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [58]:
matr = np.random.randint(0,10,(3,4,3,4))
matr.sum(axis=(-2,-1))

array([[57, 52, 40, 60],
       [60, 46, 54, 56],
       [45, 60, 52, 32]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [59]:
vec1 = np.random.uniform(0,1,(5,5))
vec2 = np.random.uniform(0,1,(5,5))

np.diag(np.dot(vec1, vec2))

array([1.68498283, 1.39196075, 1.17599618, 2.22650483, 0.42014359])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [61]:
vec = np.array([1,2,3,4,5])
vec_copy = np.zeros(len(vec) + (len(vec)-1)*3)
vec_copy[::3+1] = vec
vec_copy

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [62]:
vec1 = np.ones((5,5,3))
vec2 = 2*np.ones((5,5))

vec1 * vec2[:,:,None]

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

#### 72. How to swap two rows of an array? (★★★)

In [63]:
vec = np.arange(25).reshape(5,5)
vec[[0,1]] = vec[[1,0]]
vec

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [64]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
A

array([1, 1, 2, 3, 4, 4, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [65]:
np.lib.stride_tricks.sliding_window_view(np.arange(20), window_shape=3).mean(axis=-1)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [66]:
np.lib.stride_tricks.sliding_window_view(np.arange(10), window_shape=3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [67]:
vec = np.random.randint(0,2,100)
np.logical_not(vec, out=vec)


vec = np.random.uniform(-1.0,1.0,100)
np.negative(vec, out=vec)

array([-0.68939838, -0.02470756, -0.56995908,  0.17776907,  0.09535515,
       -0.56005851,  0.79055303, -0.00778606,  0.76835361, -0.07606826,
       -0.58380254, -0.0593486 ,  0.83788205, -0.34826676, -0.76090257,
        0.72422485, -0.83393486,  0.77866536,  0.63532785, -0.77409703,
        0.2879834 ,  0.35241278,  0.78428453,  0.52210156,  0.48424747,
        0.20737531, -0.53529902,  0.05834196, -0.98870863, -0.02123811,
        0.79496089, -0.81510134, -0.42800836,  0.53266855, -0.44498889,
       -0.1623872 ,  0.1085521 , -0.037238  , -0.65335002,  0.2340725 ,
       -0.76242158,  0.23790615, -0.80314968, -0.63656465,  0.20899323,
        0.229743  , -0.00356073, -0.3569301 , -0.36890671, -0.45623215,
       -0.91404089,  0.08760127, -0.84607377,  0.41520282, -0.62899301,
        0.58964515,  0.06888239, -0.93445889,  0.11478838,  0.67371737,
       -0.52957635,  0.09383919,  0.40247504,  0.61823879,  0.86765914,
        0.19606698,  0.76396245,  0.20741551,  0.41958516, -0.08

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [68]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))


P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

distance(P0, P1, p)

array([14.06257004, 12.17738084, 10.93336306, 14.06436664,  6.56194939,
       12.29190874,  3.65329024,  4.83305997,  0.39397485,  9.17882399])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [69]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))

np.array([distance(P0,P1,p_i) for p_i in p])

array([[17.07707524,  3.4273979 ,  7.55870792,  3.04143321,  7.03115652,
         7.58935978,  7.47876749,  9.70782563,  5.99878799,  8.22902582],
       [ 0.62632193, 13.70175239,  7.49087701, 10.3610082 ,  8.8521008 ,
         1.19355426,  1.1963364 ,  7.5039646 ,  9.76063875,  4.79540209],
       [ 5.3999704 , 10.59531059,  1.18863973,  1.3076296 ,  3.33631059,
         6.28320865,  6.31853966,  5.22920771, 11.30772496,  2.75124136],
       [18.36244799,  3.72647024,  9.8135575 ,  1.3939593 ,  8.77778312,
         2.88566175,  2.76330372,  9.53627953,  3.81787226, 11.34710558],
       [ 3.91856041,  9.37628919,  5.41074761, 12.23234633,  6.11002346,
         6.96678   ,  6.94938335,  2.75000002,  3.66019765,  4.00261373],
       [ 3.716471  , 11.081379  ,  4.04393573,  6.7660447 ,  5.5780261 ,
         0.59504316,  0.61522812,  5.14220549,  8.76111314,  1.14191599],
       [ 9.16590778,  4.39250271,  0.11207367,  8.11344573,  0.81020857,
         6.60392782,  6.54902519,  2.03983317

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [70]:
np.lib.stride_tricks.sliding_window_view(np.arange(1, 15, dtype=np.uint32), window_shape=4)

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

#### 82. Compute a matrix rank (★★★)

In [71]:
np.linalg.matrix_rank(np.random.uniform(0,1,(10,10)))

10

#### 83. How to find the most frequent value in an array?

In [72]:
np.bincount(np.random.randint(0,10,50)).argmax()

5

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [73]:
np.lib.stride_tricks.sliding_window_view(np.random.randint(0,5,(10,10)), window_shape=(3, 3))

array([[[[0, 2, 1],
         [0, 2, 3],
         [4, 1, 4]],

        [[2, 1, 4],
         [2, 3, 2],
         [1, 4, 1]],

        [[1, 4, 1],
         [3, 2, 0],
         [4, 1, 4]],

        [[4, 1, 4],
         [2, 0, 2],
         [1, 4, 2]],

        [[1, 4, 1],
         [0, 2, 1],
         [4, 2, 0]],

        [[4, 1, 0],
         [2, 1, 4],
         [2, 0, 2]],

        [[1, 0, 3],
         [1, 4, 1],
         [0, 2, 4]],

        [[0, 3, 1],
         [4, 1, 4],
         [2, 4, 2]]],


       [[[0, 2, 3],
         [4, 1, 4],
         [1, 2, 2]],

        [[2, 3, 2],
         [1, 4, 1],
         [2, 2, 1]],

        [[3, 2, 0],
         [4, 1, 4],
         [2, 1, 1]],

        [[2, 0, 2],
         [1, 4, 2],
         [1, 1, 3]],

        [[0, 2, 1],
         [4, 2, 0],
         [1, 3, 3]],

        [[2, 1, 4],
         [2, 0, 2],
         [3, 3, 3]],

        [[1, 4, 1],
         [0, 2, 4],
         [3, 3, 0]],

        [[4, 1, 4],
         [2, 4, 2],
         [3, 0, 1]]],


    

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [74]:
np.lib.stride_tricks.sliding_window_view(np.ones((16,16)), window_shape=(4, 4))[::4, ::4, ...].sum(axis=(-2, -1))

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [75]:
vec = np.arange(10000)
vec.sort()
vec[-1:-5:-1]

array([9999, 9998, 9997, 9996])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

In [76]:
vec = np.array([("Hello", 2.5, 3), ("World", 3.6, 2)])

np.core.records.fromarrays(vec.T, names='col1, col2, col3', formats = 'S8, f8, i8')

rec.array([(b'Hello', 2.5, 3), (b'World', 3.6, 2)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [77]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

378 ms ± 56.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
320 ms ± 47.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
280 ms ± 21.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [78]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)

np.where(C.any((3,1)).all(1))[0]

array([2, 4, 7])

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [79]:
np.unpackbits(np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)[:, np.newaxis], axis=1)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [80]:
print(np.unique(np.random.randint(0,2,(6,3)), axis=0))

[[0 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)